---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 7empest15.
--- DateTime: 11/09/2022 11:19
---

RegisterCommand("co", function(source, args, rawcommand)
    local pos = GetEntityCoords(PlayerPedId())
    print(pos.x .. ", " .. pos.y .. ", " .. pos.z)

end, false)

Citizen.CreateThread(function()
   

    while true do

        local interval = 1
        local pos = GetEntityCoords(PlayerPedId())
        
        --get locations in config and draw markers
        for k, v in pairs(config.locations) do
            local enter = v.positions.exit
            local exit = v.positions.enter
            local enterMarker = v.markers.exit
            local exitMarker = v.markers.enter
            local exitText = v.markers.enter.text
            local enterText = v.markers.exit.text

            

            if GetDistanceBetweenCoords(pos, enter, true) > enterMarker.drawDistance and GetDistanceBetweenCoords(pos, exit, true) > exitMarker.drawDistance then
            else
                interval = 1
                --draw enter marker
                DrawMarker(enterMarker.type, enter.x, enter.y, enter.z - 1 , 0, 0, 0, 0, 0, 0, enterMarker.scale.x, enterMarker.scale.y, enterMarker.scale.z, enterMarker.color.x, enterMarker.color.y, enterMarker.color.z, enterMarker.opacity, 0, 0, 0, 0, 0, 0)
                --draw exit marker
                DrawMarker(exitMarker.type, exit.x, exit.y, exit.z - 1, 0, 0, 0, 0, 0, 0, exitMarker.scale.x, exitMarker.scale.y, exitMarker.scale.z, exitMarker.color.x, exitMarker.color.y, exitMarker.color.z, exitMarker.opacity, 0, 0, 0, 0, 0, 0)

                if GetDistanceBetweenCoords(pos, enter, true) < 1 then
                    --draw text
                    drawNotif("TEXT-HELP",enterText.text)
                    if IsControlJustPressed(0, 38) then
                        SetEntityCoords(PlayerPedId(), exit)
                    end
                end
                if GetDistanceBetweenCoords(pos, exit, true) < 1 then
                    --draw text
                    drawNotif("TEXT-HELP",exitText.text)
                    if IsControlJustPressed(0, 38) then
                        SetEntityCoords(PlayerPedId(), enter)
                    end
                end
                end

        end

        Citizen.Wait(interval)

    end
end)


function drawNotif( id, text )
    AddTextEntry(id, text)
    DisplayHelpTextThisFrame(id, false)
end